# Generated by Django 3.2.5 on 2021-10-06 06:34

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200, unique=True)),
                ('productTitle', models.CharField(max_length=200, unique=True)),
                ('productKeyword', models.TextField(blank=True)),
                ('productSlug', models.SlugField(unique=True)),
                ('productDescription', froala_editor.fields.FroalaField()),
                ('productSiteDescription', models.TextField(blank=True)),
                ('ProductPrice', models.FloatField()),
                ('productImage', models.ImageField(upload_to='Images/products/%Y/%m/%d/')),
                ('productStock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('productCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variationCategory', models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=50)),
                ('variationValue', models.CharField(default='black', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store/products')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'product gallery',
                'verbose_name_plural': 'product gallery',
            },
        ),
    ]
